"""switch coordinates to geometry point object in buildings table

Revision ID: 6ffac3014940
Revises: 1e9b2b7d8d79
Create Date: 2026-02-03 09:42:57.611111

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ffac3014940"
down_revision: Union[str, Sequence[str], None] = "1e9b2b7d8d79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buildings",
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
    )
    # Drop index if it exists to avoid DuplicateTable error
    op.execute("DROP INDEX IF EXISTS idx_buildings_location")
    op.create_index(
        "idx_buildings_location",
        "buildings",
        ["location"],
        unique=False,
        postgresql_using="gist",
    )

    op.create_index(
        "idx_buildings_location_geog",
        "buildings",
        [sa.text("CAST(location AS geography)")],
        postgresql_using="gist",
    )

    op.drop_column("buildings", "longitude")
    op.drop_column("buildings", "latitude")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "buildings",
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "buildings",
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )

    op.drop_index(
        "idx_buildings_location_geog", table_name="buildings", postgresql_using="gist"
    )

    op.drop_index(
        "idx_buildings_location", table_name="buildings", postgresql_using="gist"
    )
    op.drop_column("buildings", "location")

    # ### end Alembic commands ###
